


def readOutputCSV(fname):
    """Reads the output file generated by the scheduler engine
    and returns a formatted string that can be read by the GUI."""

    result = ""

    output_file = file(fname, 'r')

    for line in output_file:
        result += line

    return result
